### PR TITLE
merged gitsite and rsvpsite

### PR DESCRIPTION
**Pull request by RachellCalhoun**
So i added all the files from the github page, added some photos and fixed up the format so it's the same on all pages with base.html. I left old files named as name01 and new modified files are original name. (sorry about all the files!)

### CODE REVIEW

**Comment by RachellCalhoun** [comment]
I found a problem. Wait please

**Comment by hassanabidpk** [comment]
ok

**Comment by hassanabidpk** [comment]
Any progress on this ? I just checked it on my computer.

**Comment by RachellCalhoun** [comment]
screenshot from 2016-03-10 11 00 15
screenshot from 2016-03-10 11 18 07

**Comment by hassanabidpk** [comment]
screen shot 2016-03-10 at 12 22 40 pm

Probably we should adjust the menu on mobile also ? @RachellCalhoun

**Comment by hassanabidpk** [comment]
Its looks good to me. Shall I merge it ? and we fix minor issues in patches?

**Comment by RachellCalhoun** [comment]
Sounds good!

**Pull request merged**
